Repository tari-project/rfcs, pull requests merged in 2022-11, with the labels that each got.

#37 feat: stabilise rfc-0203
  src/RFC-0203_StealthAddresses.md
Labels: CR-insufficient_context, P-merge, P-reviews_required

#34 feat: stabilise rfc-0131
  src/RFC-0131_Mining.md
Labels: P-merge

#36 feat: stabilise rfc-0173
  src/RFC-0173_Versioning.md
Labels: P-merge

#38 docs: dan v2 overview
  src/Glossary.md
  src/RFC-0171_MessageSerialisation.md
  src/RFC-0303_DanOverview.md
  src/RFC-0320_TurbineModel.md
  src/RFCD-0300_DAN.md
  src/RFCD-0301_NamespaceRegistration.md
  src/RFCD-0302_ValidatorNodes.md
  src/RFCD-0304_VNCommittees.md
  src/RFCD-0306_DANTemplateRegistration.md
  src/RFCD-0311_AssetTemplates.md
  src/RFCD-0312_DANHighLevelSpecification.md
  src/RFCD-0322_VNRegistration.md
  src/RFCD-0340_VNConsensusOverview.md
  src/RFCD-0341_AssetRegistration.md
  src/RFCD-0345_AssetLifeCycle.md
  src/RFCD-0360_NFTInvoices.md
  src/RFCD-0500_PaymentChannels.md
  src/SUMMARY.md
  src/assets/turbine.png
Labels: P-merge, P-reviews_required, CR-too_long

#42 fix(htlc stabilising): update htlc rfcs
  src/RFC-0202_TariScriptOpcodes.md
  src/RFC-0230_HTLC.md
Labels: P-merge

#51 docs: rfc-0250 covenants stabilized
  src/RFC-0250_Covenants.md
Labels: P-acks_required

#41 fix(stable base nodes): minor updates and move to stable
  src/Glossary.md
  src/RFC-0110_BaseNodes.md
Labels: P-acks_required

#44 docs: update rfc172
  src/RFC-0172_PeerToPeerMessagingProtocol.md
Labels: CR-insufficient_context, P-acks_required

#54 docs: update rfc0201-tariscript
  src/RFC-0201_TariScript.md
  src/RFC-0204_TariScriptExamples.md
  src/SUMMARY.md
Labels: CR-insufficient_context, CR-too_long

#48 docs: update Emoji ID
  src/RFC-0152_EmojiId.md
Labels: P-acks_required, P-reviews_required

#53 chore: refreshed rfc-0190/mempool
  src/RFC-0190_Mempool.md
Labels: P-merge

#59 docs: rfc-0152 small improvements
  src/RFC-0152_EmojiId.md
Labels: P-acks_required

#25 docs: move RFC_0120 to stable
  src/Glossary.md
  src/RFC-0120_Consensus.md
Labels: P-merge, P-reviews_required

#24 docs: vnc selection
  src/RFC-0314-VNCSelection.md
Labels: CR-insufficient_context, P-acks_required, P-reviews_required, T-DAN Layer

#60 docs: add changelog to rfc-0140
  src/RFC-0140_Syncing_and_seeding.md
Labels: P-acks_required
