Repository tari-project/rfcs, pull requests merged in 2022-10, with the labels that each got.

#20 fix(rfc201): clarify high level process of TariScript
  src/RFC-0201_TariScript.md
Labels: CR-insufficient_context

#29 fix(rfc-171): update to include protobuf
  src/RFC-0171_MessageSerialisation.md
Labels: P-merge

#30 docs: rfc_240 add change log
  src/RFC-0240_AtomicSwap.md
Labels: CR-insufficient_context

#14 feat: add aggregate signatures to transaction inputs and outputs
  src/RFC-0201_TariScript.md
  src/RFC-0202_TariScriptOpcodes.md
Labels: S-Controversial, P-acks_required

#33 fix: clean up organisation of rfcs
  .github/workflows/rfc_test.yml
  src/RFC-0123_One_sided_replay_attacks.md
  src/RFC-0130_Mining.md
  src/RFC-0345_AssetLifeCycle.md
  src/RFC-0388_BearerTokens.md
  src/RFC-0500_PaymentChannels.md
  src/SUMMARY.md
  src/deprecated.md
  src/proposals.md
Labels: P-acks_required

#31 fix: update fields of 132
  src/RFC-0132_Merge_Mining_Monero.md
Labels: P-merge

#35 feat: stabilise rfc-0171
  src/RFC-0171_MessageSerialisation.md
Labels: P-merge
