Repository tari-project/rfcs, pull requests merged in 2023-12, with the labels that each got.

#114 ci(fix): prevent code injection
  .github/workflows/pr_title.yml
Labels: CR-insufficient_context, P-acks_required

#115 chore: edits and numbering fix
  src/RFC-0305_Consensus.md
  src/RFC-0330_Cerberus.md
  src/SUMMARY.md
Labels: P-acks_required, P-reviews_required

#113 docs: update documentation for `ToRistrettoPoint` opcode
  src/RFC-0202_TariScriptOpcodes.md
Labels: P-acks_required

#118 feat: cerberus detail
  src/RFC-0305_Consensus.md
  src/RFC-0330_Cerberus.md
  src/theme/index.hbs
  src/theme/js/mermaid.min.js
Labels: P-acks_required, P-reviews_required

#116 chore: add epoch management to summary
  src/RFC-0305_DanTimeManagement.md
  src/RFC-0325_DanTimeManagement.md
  src/SUMMARY.md
Labels: P-acks_required, P-reviews_required

#119 fix: remove old maintainers
  src/RFC-0111_BaseNodeArchitecture.md
  src/RFC-0131_Mining.md
  src/RFC-0140_Syncing_and_seeding.md
  src/RFC-0150_Wallets.md
  src/RFC-0153_StagedWalletSecurity.md
  src/RFC-0160_BlockSerialization.md
  src/RFC-0170_NetworkCommunicationProtocol.md
  src/RFC-0172_PeerToPeerMessagingProtocol.md
  src/RFC-0173_Versioning.md
  src/RFC-0190_Mempool.md
  src/RFC-0201_TariScript.md
  src/RFC-0203_StealthAddresses.md
  src/RFC-0230_HTLC.md
  src/RFC-8003_TariUseCases.md
  src/RFCD-0010_CodeStructure.md
  src/RFCD-0130_Mining.md
  src/RFCD-0300_DAN.md
  src/RFCD-0302_ValidatorNodes.md
  src/RFCD-0304_VNCommittees.md
  src/RFCD-0341_AssetRegistration.md
  src/RFCD-0360_NFTInvoices.md
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#107 feat: stablecoin draft specification
  book.toml
  src/RFC-0385_StableCoins.md
  src/SUMMARY.md
  src/assets/tether.sol
  src/assets/usdc.sol
Labels: P-acks_required, P-reviews_required, CR-too_long

#120 fix: stablecoin rfc title
  src/RFC-0385_StableCoins.md
  src/SUMMARY.md
Labels: P-acks_required, P-reviews_required

#121 fix: typos and small fixes
  src/RFC-0385_StableCoins.md
Labels: P-acks_required

#124 Upgrade mdbook
  .github/workflows/rfc_deploy.yml
Labels: P-acks_required, P-reviews_required

#126 fix: upgrade mdbook-mermaid
  .github/workflows/rfc_deploy.yml
Labels: CR-insufficient_context

#125 fix: remove old mermaid version
  .github/workflows/rfc_deploy.yml
  book.toml
  mermaid-init.js
  mermaid.min.js
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#127 fix: fix mermaid again
  .github/workflows/rfc_deploy.yml
  .github/workflows/rfc_test.yml
  book.toml
Labels: P-acks_required, P-reviews_required

#128 feat: update content for rfc-331
  src/RFC-0331_Indexers.md
Labels: CR-insufficient_context, P-acks_required, P-reviews_required
